language: php
php:
  - '5.5'
  - '7.0'
services:
  - docker

addons:
  ssh_known_hosts: 192.155.88.91

  apt:
    - sshpass

before_install:

  # Add our SSH key for deploy func
  openssl aes-256-cbc -K $encrypted_38df744560e6_key -iv $encrypted_38df744560e6_iv -in travis.id_rsa.enc -out $HOME/.ssh/travis.id_rsa -d

install:

  # Install composer deps
  - composer install

script:

  # Run code and styling
  - composer test

after_success:

  # Set up the SSH key and config
  - chmod 600 $HOME/.ssh/travis.id_rsa
  - eval "$(ssh-agent)"
  - ssh-add $HOME/.ssh/travis.id_rsa
  - cp -rf ssh-config $HOME/.ssh/config

  # Set a user for things
  - git config --global user.name "Travis Bot"
  - git config --global user.email "geoff@thinktandem.io"

  # Set up our repos
  - git remote add upstream ssh://gff@192.155.88.91/var/www/backdrop

  # We need to re-add this in because our clone was originally read-only
  - git remote rm origin
  - git remote add origin git@github.com:thinktandem/githook-workflow-demo.git
  - git checkout $TRAVIS_BRANCH

  # Pull in any remote changes
  - git pull upstream $TRAVIS_BRANCH

  # And then deploy
  - git push upstream $TRAVIS_BRANCH

  # Run the post git tasks in deploy_backdrop.sh
  - sshpass -e ssh gff@192.155.88.91 /home/gff/code/deploy_scripts/deploy_backdrop.sh
